---
apiVersion: build.openshift.io/v1
spec:
  source: 
    type: "Binary" 
  output:
    to:
      kind: DockerImage
      name: nexus-docker-registry-nexus3.192.168.1.255.xip.io/vf/${project.artifactId}:${jgitver.calculated_version}
    pushSecret:
      name: nexus  
  strategy:
    dockerStrategy:
      dockerfilePath: ./Dockerfile
    type: Docker
  triggers:
    - type: ConfigChange