apiVersion: build.openshift.io/v1
spec: 
  output:
    to:
      kind: DockerImage
      name: nexus-docker-registry-nexus3.192.168.1.255.xip.io/vf/${project.artifactId}:${jgitver.calculated_version}
    pushSecret:
      name: nexus  
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: docker.io/fabric8/s2i-java
    type: Docker