spec:
  template:
    spec:
      containers:
        - env:
            - name: JAVA_APP_JAR
              value: /deployments/${project.artifactId}-${project.version}.jar
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: postgresql
                  optional: false
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgresql
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgresql
                  optional: false
            - name: SPRING_PROFILES_ACTIVE
              value: beta